### ISSUE TITLE
Itly.load context and validation options

### ISSUE THREAD

**Issue by OleksiiFomazov** [amplitude/ampli-examples#107]
Hey Ampli team!

I'm migrating from an Itly runtime and use [this guide](https://www.docs.developers.amplitude.com/data/sdks/browser-ampli/#migrating-from-an-itly-runtime).
Unfortunately, I can't find any way to implement already exising in our code `context` [option](https://www.docs.developers.amplitude.com/data/deprecated-sdks/browser/#load) and `itly.page` [method](https://www.docs.developers.amplitude.com/data/deprecated-sdks/browser/#page).
Could you give me please some reference how I can upgrade them? Thanks in advance!

![image](https://user-images.githubusercontent.com/76514685/172365133-8c9cb41f-4f77-4c13-ace5-c991ec924d72.png)

**Comment by OleksiiFomazov** [comment]
The same for `itly.validation` option:
![image](https://user-images.githubusercontent.com/76514685/172404480-2e74c734-91f6-4bda-a055-0e164590de34.png)

**Comment by OleksiiFomazov** [comment]
I got some answers in another place, I leave it here for those who have encountered similar questions.

The `context` parameter is no longer supported in Ampli.
This was originally based on per Source Templates which is a feature that has since been deprecated.
However, if you would like to add additional data on each Event you can do so by creating a Middleware like below that will set "contextProp=true" on all Events.

> [https://www.docs.developers.amplitude.com/data/ampli/middleware/](https://www.docs.developers.amplitude.com/data/ampli/middleware/)

```
 export const contextMiddleware:Middleware = (payload, next) => {
   payload.event.event_properties = {
     ...payload.event.event_properties,
     contextProp: true,
   };
   next(payload);
 };
```
The `validation` parameter is also no longer supported in Ampli. This flag previously enabled/disabled local schema validation in the SDK. The new Ampli SDKs no longer do local schema validation and instead rely on backend validation on our servers which can be viewed in the Event "sparklines" in the Events page in Data.

The `itly.page` method has actually been deprecated in favor of [event-based analytics](https://help.amplitude.com/hc/en-us/articles/5447814048795#h_fec80838-397a-409e-a32b-bd116ff75d85). I believe you’re using Segment, so if you still need the page call for Segment (or something else downstream), you can leverage Middleware to check for your page event and forward using the underlying Segment.

**Comment by justin-fiedler** [comment]
Thanks @OleksiiFomazov for sharing the answers here. I also made a ticket to add this information to our SDK migration documentation.
