### ISSUE TITLE
ampli __init__.py

### ISSUE THREAD

**Issue by brokengrappler** [amplitude/ampli-examples#135]
Every time I run an ampli pull, one of the classes listed in the ```__init__.py``` is Group, which isn't a class defined in my ampli.py file. Is there something I need to do in the UI to make sure codegen includes the Group class or is there a way to have ```__init__.py``` exclude Group if it's not specifically defined in the UI?

As-is, I have to delete Group from ```__init__.py``` every time i ampli pull.

**Comment by bohan-amplitude** [comment]
Hi @brokengrappler Thank you for your feedback. I'll look into the issue and fix it asap.

**Comment by RZachLamberty** [comment]
I see the same thing, and also for the `Identify` class

**Comment by brokengrappler** [comment]
@RZachLamberty my generated ampli.py happens to have the ```Identify``` class. Hopefully that helps with the debugging @bohan-amplitude.

**Comment by bohan-amplitude** [comment]
@RZachLamberty @brokengrappler Thanks very much for the information. I have made a fix and merged to our backend service code base. The fix will on production once the deploy finished. Please check with `ampli pull` later.
