### ISSUE TITLE
`minIdLength` track option isn't being passed correctly

### ISSUE THREAD

**Issue by ryanechternacht** [amplitude/ampli-examples#150]
```
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 3
 * Build: 1.0.0
 * Runtime: browser:javascript-ampli-v2
```

According to [the documentation](https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/#user-properties-are-details-about-your-user), there is a `min_id_length` property that can be passed to `https://api2.amplitude.com/2/httpapi` to allow shorter user ids. To set this, an option needs to be passed when the sdk loads (in `.load()`). The relevant code is here

```
  load(options) {
 ...

    const env = options?.environment ?? 'development';
    const apiKey = options?.client?.apiKey ?? ApiKey[env];

    if (options?.client?.instance) {
      this.amplitude = options?.client?.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...options?.client?.configuration });
    } ...
  }
```

The value should be passed along in the 3rd property of `this.amplitude.init()`, but here we are only pulling out the `client.configuration` property. I manually modified the line as follows and it now works correctly

```
return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...options?.client?.configuration, minIdLength: options?.minIdLength ?? 5 });
```
  
Notes:
1. According to the documentation (and my testing), the property should be called `minIdLength` when passed through the sdk
2. The default value is 5, so I used a form that would maintain the default if no value was set (there are other ways to set that up).
3. This is the only value that can be set currently (AFAIK), but future proofing this is probably a better idea. I just wasn't sure what happens if I pass in keys that aren't expected.

**Comment by kevinpagtakhan** [comment]
Hi @ryanechternacht, thank you for choosing Amplitude and your submitting your feedback. `minIdLength` is a key in `options?.client?.configuration` so I believe you should be able to pass it like the following code sample:

```ts
ampli.load({
  client: {
    configuration: {
      minIdLength: 5,
    },
  },
});
```

Let me know if this solves the issue, otherwise we're happy to provide more support.

**Comment by ryanechternacht** [comment]
Interesting, I'll give that a shot. 

Where would I find the documentation that tells me that's how it's supposed to work?

**Comment by kevinpagtakhan** [comment]
@ryanechternacht The ampli SDK you are using wraps `@amplitude/analytics-browser` SDK and docs can be found here: https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/, and specifically for configuration here: https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#configuration

**Comment by ryanechternacht** [comment]
Sweet thanks. That worked. 

I had not actually found the sdk docs and was using the general web call docs and trying to piece it together. 

Can you add a link here to the `ampli` cli somewhere? maybe in `ampli pull` since that's the path the docs send you down.

**Comment by kevinpagtakhan** [comment]
@ryanechternacht yes, we'll consider this issue as feedback to make an update to our dev docs.
